package com.twitter.config.exception;

public enum ConfigLoaderError {
    INVALID_PROPERTY_KEY,
    INVALID_PROPERTY_VALUE,
    INVALID_CONFIG_FILE_PATH_VALUE,
    CONFIG_FILE_NOT_FOUND,
    PROPERTY_GROUP_NULL,
    INVALID_PROPERTY_DEFINITION,
    FAILED_TO_READ_CONFIG_FILE,
    PROPERTY_NOT_FOUND, 
    PROPERTY_GROUP_NOT_FOUND;
}
